---

- name: Install Requirements
  sudo: yes
  pip: name=gunicorn state=present

- name: Create gunicorn Upstart Job
  sudo: yes
  template: "src=django.conf.j2 dest=/etc/init/{{ django_project_name }}.conf"

- name: Start gunicorn Upstart Job
  sudo: yes
  service: name={{ django_project_name }} state=restarted
