django_project_name: delivercute
django_home: "/home/ubuntu/{{ django_project_name }}"
remote_repo: https://github.com/WillWeatherford/django-imager.git
rds_db_instance: imagerdb
settings_file: "{{ django_project_name }}.production_settings"
wsgi_file: "{{ django_project_name }}.wsgi"
